### PR TITLE
test: split test files

### PR DESCRIPTION
**Pull request by LittleSound**
Referencing compiler-core/compiler-dom, the tests are split into multiple files for easy copying of other tests.

Vapor is a combination of core and dom. Some features that vapor calls from core do not need to be tested. It is necessary to merge the tests of dom and core into vapor. For example, vOn.spec.ts from both core and dom can be merged into one in vapor.

### CODE REVIEW

**Comment by LittleSound** [comment]
@sxzz I want to confirm one thing, should `compile()` in `__tests__/transform` be changed to `transform()` like in compiler-core/dom?

an example: [/packages/compiler-core/__tests__/transforms/vBind.spec.ts](https://github.com/vuejs/core/blob/597ada36ed1c5da8d9ba922c4514b4e384671020/packages/compiler-core/__tests__/transforms/vBind.spec.ts)

**Comment by sxzz** [comment]
Yes, we should separate IR transforming and codegen part.

**Review by sxzz — COMMENTED** [review]
LTGM but I think we should rename `.test.ts` to `.spec.ts` for better consistence.

**Comment by LittleSound** [comment]
> LTGM but I think we should rename `.test.ts` to `.spec.ts` for better consistence.

Sure, I'll take care of it right away.

**Comment by LittleSound** [comment]
> Yes, we should separate IR transforming and codegen part.

If you plan to merge this PR as soon as possible, I can create a new PR later to do it.

**Pull request merged**
