### PR TITLE
wip: template component support 

### PR DESCRIPTION
**Pull request by pikax**
Simple support for rendering component. 

Implementation can be better, still work in progress.

### CODE REVIEW

**Comment by sxzz** [comment]
I don't know why but I cannot re-open the PR. It will be closed immediately. I have no idea about this.

**Comment by Ubugeeei** [comment]
It seems I can't specify core-vapor from the branch I created before.
I'll try creating a sub-branch directly under core-vapor :D

スクリーンショット 2024-01-28 22 25 08

**Comment by sxzz** [comment]
Actually, @Ubugeeei has write access to this repo and can push your branch directly without a fork.

**Comment by Ubugeeei** [comment]
Yes, that method worked well :D

**Pull request closed without merging**
