### PR TITLE
fix: do not wrap registering event listeners under effect

### PR DESCRIPTION
**Pull request by ydcjeff**
Before:
```ts
  _effect(() => {
    _on(n7, "click", _ctx.inc);
  });
  _effect(() => {
    _on(n8, "click", _ctx.dec);
  });
```

After:

```ts
  _on(n7, "click", _ctx.inc);
  _on(n8, "click", _ctx.dec);
```

### CODE REVIEW

**Review by LittleSound — APPROVED** [review]

**Review by baiwusanyu-c — APPROVED** [review]

**Review by sxzz — COMMENTED** [review]
event handler could be changed, so effect is necessary.

**Comment by ydcjeff** [comment]
@sxzz Do you mean reactive event handler?

**Comment by sxzz** [comment]
@ydcjeff Yes

**Comment by ydcjeff** [comment]
Interesting! I didn't happen to see in the Vue docs tho.

**Comment by ydcjeff** [comment]
I tried [reactive event handler](https://play.vuejs.org/#eNp9UstOAjEU/ZWbboTIw4S4wYH4CAtdqFGX3YzlDhQ67aS9BZLJ/LudR5FEZDOZ3vPo6WlL9lAUo51HNmWJE1YWBA7JF3OuZV4YS1CCxWwA+5TEepFlKAgqyKzJ4SrorrjmWhjtCITxmmBW03s3/bs4llqEYa8Ps3lLGe1S5fH6OhKWeJYwHEbCOtVLhbazDn61OdcniXqtuuQaQGbQO7GBOdz2WwSiU4fM6q2DFUBVf1A5/KNOYPi/PESJ8qrPdTJuGwzdhQVhXqiUMKwAkm9PZDTcCyXFdsZZZ8XZvCy75qoqGbe0IEnGJ3o2YORCF5lcjTbO6HBZTSLOhMkLGXzeCpKhK86mMStnqVJm/9LMyHocxLlYo9iemW/coZ5x9m7Rod0hZ0eMUrtCauHF5ysewv8RzM3Sq8C+AH6gM8rXGVvao++Of+Q1aZ+bJyf16sstDoTaxUPVQZumGz5n4eU9XTj6b9zJaBJviFU/Y4r4Qg==) in the Vue SFC playground, and found that Vue wraps that handler with inline function.

```ts
    onClick: _cache[0] || (_cache[0] = (...args) => (handler.value && handler.value(...args)))
```

So I still think we do not need wrap under effect.

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Review by sxzz — APPROVED** [review]

**Pull request merged**
