### PR TITLE
ci: continuous releases with pkg.pr.new

### PR DESCRIPTION
**Pull request by Aslemammad**
I didn't remove the release file completely, for now let's just see if this works by just adding pkg.pr.new! 

Before running the workflows for this PR, the [github app](https://github.com/apps/pkg-pr-new) should be installed! 

Thank you so much @sxzz for the opportunity!

### CODE REVIEW

**Comment by sxzz** [comment]
Release job is skipped

**Comment by sxzz** [comment]
CI failed 🤔

**Comment by Aslemammad** [comment]
yea I missed the command! Now let's see if it works.

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Great! Thanks for your contribution and `pkg.pr.new`!

By the way, if we can select specific packages to display in the comments, it will look better.
https://github.com/vuejs/core-vapor/pull/264#issuecomment-2253232476

**Comment by Aslemammad** [comment]
Thank you so much for the opportunity, Kevin! 

Yep, I agree, I'm looking to find ways on how to decrease the space each comment uses, I'll do my best to come up with something good.

**Comment by sxzz** [comment]
https://github.com/vue-macros/vue-macros/pull/746#issuecomment-2253790813

I also added pkg.pr.new to Vue Macros, the comment content is really too long. Maybe we can use <details> to fold it.

**Comment by Aslemammad** [comment]
Thank you so much, Sure, I just fixed this issue, will keep you updated on new release! 

What do you think about this format? https://github.com/stackblitz-labs/pkg.pr.new/pull/156#issuecomment-2247757002

**Comment by sxzz** [comment]
Looks good, thank you!

**Pull request merged**
