### PR TITLE
feat: basic implementation of v-memo for dom

### LINKED ISSUE #18: `v-memo`
`v-memo` in vapor mode is completely different, compared to vue-core. Since in vapor mode, we use `effect` (aka `watchEffect`) to track & update DOM nodes.

So to implement it, I think `watch` function is enough. 
```html
<div v-memo="[msg]">{{ msg }}{{ count }}</div>
```

Compiles to

```ts
watch([msg], () => {
  setText(...)
})
```

---

- [ ] Runtime `watch` function
- [ ] Compiler part

### PR DESCRIPTION
**Pull request by baiwusanyu-c**
This PR implements the v-memo directive function on the dom. No tests have been added yet because I am not sure whether this implementation is elegant. Maybe I need some guidance.

closes #18

### CODE REVIEW

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Comment by baiwusanyu-c** [comment]
```
<script setup lang="ts">
import { ref, computed } from 'vue'
const count = ref(1)
const html = computed(() => `<button>HTML!</button>`)
const handleClick = () => {
  count.value++
}
// @ts-expect-error
globalThis.count = count
// @ts-expect-error
globalThis.html = html
// @ts-expect-error
globalThis.handleClick = handleClick
</script>

<template>
  <div v-memo="[html]" @click="handleClick">
    <div>The number is {{ count }}.</div>
    <div v-memo="[count]">
      {{ count }}
    </div>
  </div>
</template>

```

**Comment by baiwusanyu-c** [comment]
```
import { defineComponent as _defineComponent } from "vue";
import { ref, computed } from "vue";
const _sfc_main = /* @__PURE__ */ _defineComponent({
  __name: "App",
  setup(__props, { expose: __expose }) {
    __expose();
    const count2 = ref(1);
    const html2 = computed(() => `<button>HTML!</button>`);
    const handleClick2 = () => {
      count2.value++;
    };
    globalThis.count = count2;
    globalThis.html = html2;
    globalThis.handleClick = handleClick2;
    const __returned__ = { count: count2, html: html2, handleClick: handleClick2 };
    Object.defineProperty(__returned__, "__isScriptSetup", { enumerable: false, value: true });
    return __returned__;
  }
});
import { template, children, createTextNode, insert, effect, on, withMemo, setText } from "vue/vapor";
const t0 = template("<div><div>The number is <!>.</div><div></div></div>");
function _sfc_render() {
  const _memoCache = [];
  const n0 = t0();
  const { 0: [n1, { 0: [n4, { 1: [n3] }], 1: [n5] }] } = children(n0);
  const n2 = createTextNode(count.value);
  insert(n2, n4, n3);
  effect(() => {
    on(n1, "click", handleClick);
  });
  effect(() => {
    withMemo([html.value], () => {
      setText(n2, void 0, count.value);
    }, _memoCache, -1);
    withMemo([count.value], () => {
      setText(n5, void 0, count.value);
    }, _memoCache, 0);
  });
  return n0;
}
```

**Comment by sxzz** [comment]
Please create an issue before feature contributing.

**Pull request closed without merging**
